name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to Staging
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PORT: 23238  # Explicitly set the port here
        run: |
          echo "Attempting to connect to $SERVER_IP..."
          ssh -v -p $SSH_PORT $DEPLOY_USER@$SERVER_IP
          if [ $? -ne 0 ]; then
            echo "Deployment failed"
            exit 1
          fi
        
      - name: Verify Deployment
        if: success()
        run: echo "Deployment to staging was successful"

      - name: Deployment Failed
        if: failure()
        run: echo "Deployment to staging failed"